# Generated by Django 3.2 on 2021-04-20 04:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0003_book'),
    ]

    operations = [
        migrations.RenameField(
            model_name='book',
            old_name='Author',
            new_name='author',
        ),
    ]
